### 에러에 적절히 대응하지 않으면 프로그램이 강제 종료 되기 때문에 에러에 적절히 대처하는 것이 매우 중요.

# try...catch...finally 문
```
try {
    //실행할 코드
} catch(err){
    //try 코드 블록에서 에러가 발생할 경우 이 블록의 코드 실행.
}finally{
    // 에러 발생과 상관없이 반드시 한 번 실행
}
```

# throw 문
- 에러를 발생시키려면 Try 코드 블록에서 throw문으로 에러 객체를 던져야 함.

# 에러의 전파
```
const foo = () => {
    throw Error("foo에서 발생한 에러");
}

const bar = () => {
    foo();
}
const baz = () => {
    bar();
}

try{
    baz();
}catch(err) {
    console.error(err)
}
```